apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-alias.force-update: 'true'
    argocd-image-updater.argoproj.io/image-alias.update-strategy: latest
  name: currency-exchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-exchange
  template:
    metadata:
      labels:
        app: currency-exchange
    spec:
      containers:
        - image: maks231docker/mmv2-currency-exchange-service:0.0.1-SNAPSHOT
          name: currency-exchange
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: currency-exchange
spec:
  selector:
    app: currency-exchange
  allocateLoadBalancerNodePorts: true
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  type: LoadBalancer

