apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-alias.force-update: 'true'
    argocd-image-updater.argoproj.io/image-alias.update-strategy: latest
  name: naming-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: naming-server
  template:
    metadata:
      labels:
        app: naming-server
    spec:
      containers:
        - image: maks231docker/mmv2-naming-server:0.0.1-SNAPSHOT
          name: naming-server
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: naming-server
spec:
  selector:
    app: naming-server
  allocateLoadBalancerNodePorts: true
  ports:
    - port: 8761
      protocol: TCP
      targetPort: 8761
  type: LoadBalancer

