apiVersion: v1
kind: Service
metadata:
  name: currency-conversion
  namespace: default
spec:
  type: ExternalName
  externalName: 34.69.108.211
#  clusterIP: 34.31.220.116
  ports:
    - port: 8100
      protocol: TCP
      targetPort: 8100