apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: mmv2-spring-cloud-config-server
          image: maks231docker/mmv2-spring-cloud-config-server:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8888


