apiVersion: apps/v1
kind: Deployment
metadata:
  name: mmv2-spring-cloud-config-server
spec:
  selector:
    matchLabels:
      app: config-server
  replicas: 2
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: spring-cloud-config-server
          image: maks231docker/mmv2-spring-cloud-config-server:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8888
