apiVersion: v1
kind: Service
metadata:
  name: config-server
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
spec:
  selector:
    app: config-server
  allocateLoadBalancerNodePorts: true
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
  type: LoadBalancer

