apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2024-07-23T06:57:35Z"
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: config-server
  name: config-server
  namespace: default
  resourceVersion: "15267592"
  uid: 871efb43-de94-42ab-b2d5-d6e8514c3581
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.239.186
  clusterIPs:
    - 34.118.239.186
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 32012
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: config-server
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 34.42.253.204
